---
title: "Open-source Healthcare Statistics"
description: "Collecting statistics on the use of open-source code in the NHS and the wider healthcare field."
comments: false
jupyter: python3
---

## What is Open-source?

Open-source is the practice of publishing the source code of a software project so that anyone can read, modify, re-use, and improve that software.

As set out in the [NHS Digital Service Manual](https://service-manual.nhs.uk/service-standard/12-make-new-source-code-open), public services are built with public money--so unless there's a good reason not to (for security reasons for example), all code produced by the NHS should be made publicly available. To this end, the [Department of Health & Social Care has recently made a commitment](https://www.gov.uk/government/publications/data-saves-lives-reshaping-health-and-social-care-with-data-draft/data-saves-lives-reshaping-health-and-social-care-with-data-draft) to make all new NHS code open source and published under appropriate licences such as [MIT](https://opensource.org/licenses/MIT) and [OGLv3](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/).

::: {.callout-note}
## Note
Please be aware that this package is in the early stages of development, and features may change.
:::

```{python}
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
from dateutil.relativedelta import relativedelta

df = pd.read_csv("../open_health_stats/data/org_repos_agg.csv")

# Convert the "Date" column to a datetime dtype
df['Date'] = pd.to_datetime(df['Date'])

# Filter the latest date for each organization
latest_dates = df.groupby('Organisation')['Date'].idxmax()
latest_df = df.loc[latest_dates]

# Create a new column with hyperlinks for the "Organisation" column
latest_df['Organisation'] = latest_df.apply(lambda x: f"[{x['Organisation']}]({x['URL']})", axis=1)

# Drop the "Date" column and sort by "Open Repositories"
latest_df = latest_df.drop(['Date', 'URL'], axis=1).sort_values('Open Repositories', ascending=False)

# Convert the sorted DataFrame to a markdown table and print it
md_table = latest_df.to_markdown(index=False)

print(md_table)
```

::: {.panel-tabset}
## Example `nhspy-plotthedots` Chart
:::

## NHS Python Community slack

If you want to learn more about this project, please join the discussion at the [NHS Python Community Slack group](https://).